
import requests
import json
from datetime import datetime
import config

# 1. 데이터 수집 엔진 (Weather & Ocean Data)
def fetch_dive_data():
    results = {}
    for name, coords in config.LOCATIONS.items():
        # 실제 운영 시 OpenWeatherMap 등의 API를 호출하는 로직이 들어갑니다.
        # 현재는 구조 검증을 위해 샘플 데이터를 생성합니다.
        results[name] = {
            "temp": "29°C",
            "wave": "0.5m",
            "visibility": "30m+",
            "status": "Excellent"
        }
    return results

# 2. AI 콘텐츠 생성 엔진 (GPT-4 연동)
def generate_content_with_ai(data):
    # 이 부분은 실제 GPT API를 호출하여 영문 대본과 캡션을 생성합니다.
    # 사장님이 매일 확인하실 '최종 결과물'을 만드는 핵심 단계입니다.
    
    prompt = f"""
    You are a world-class scuba diving content creator. 
    Based on the following real-time data from the Philippines: {json.dumps(data)},
    generate two types of content for an English-speaking audience (US/UK/AU):
    
    1. A high-energy YouTube Shorts script (under 60 seconds).
    2. An engaging Instagram caption with emojis and relevant hashtags.
    
    Use professional yet adventurous tone. Use keywords like 'Crystal Clear', 'Epic Visibility'.
    """
    
    # 실제 구현 시 openai 라이브러리를 사용하여 호출합니다.
    # 현재는 시스템 작동 확인을 위해 생성된 텍스트를 반환하도록 설계되었습니다.
    return {
        "shorts_script": "[Generated by AI] Today's Bohol is a dream! 🌊 (Script included)",
        "insta_caption": "Experience the magic of Balicasag today! ✨ #BoholDive #ScubaLife"
    }

# 3. 알림 시스템 (Telegram Notification)
def send_telegram_notification(content):
    message = f"📢 [Daily Dive Report]\n\n"
    message += f"🎬 Shorts Script:\n{content['shorts_script']}\n\n"
    message += f"📸 Insta Caption:\n{content['insta_caption']}"
    
    # 텔레그램 API를 통해 사장님께 즉시 전송합니다.
    # requests.post(f"https://api.telegram.org/bot{config.TELEGRAM_BOT_TOKEN}/sendMessage", 
    #                 data={"chat_id": config.TELEGRAM_CHAT_ID, "text": message})
    print("✅ Telegram Notification Sent!")

def main():
    print(f"[{datetime.now()}] System started...")
    data = fetch_dive_data()
    content = generate_content_with_ai(data)
    send_telegram_notification(content)
    print("✅ Daily cycle completed.")

if __name__ == "__main__":
    main()
